/***** DO NOT EDIT THIS FILE *****/
// MonkeyTalkDemo.js generated by MonkeyTalk

load("libs/MonkeyTalkAPI.js");


var MonkeyTalkDemo = {};

/*** script -- demo ***/
MonkeyTalkDemo.demo = function(app) {
	MT.Script.call(this, app, "demo.mt");
};

MonkeyTalkDemo.demo.prototype = new MT.Script;

MonkeyTalkDemo.demo.prototype.call = function() {
	//run: demo.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.demo = function() {
	return new MonkeyTalkDemo.demo(this);
};

